# Generated by Django 2.1.1 on 2018-10-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
    ]
