# Generated by Django 2.1.1 on 2018-10-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0002_auto_20181003_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='originates_in_vespawatch',
            field=models.BooleanField(default=True),
        ),
    ]
