# Generated by Django 2.1.1 on 2018-10-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0005_auto_20181009_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.Observation'),
            preserve_default=False,
        ),
    ]
