# Generated by Django 2.1.1 on 2018-10-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0006_managementaction_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='nest_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='observation',
            name='inaturalist_species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
