# Generated by Django 2.1.2 on 2018-10-11 13:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0008_auto_20181011_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='inaturalist_pull_taxons_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, help_text='When pulling observations from iNaturalist, reconcile according to those IDs.', null=True, size=None),
        ),
        migrations.AddField(
            model_name='species',
            name='inaturalist_push_taxon_id',
            field=models.BigIntegerField(blank=True, help_text="When pushing an observation to iNaturalist, we'll use this taxon_id", null=True),
        ),
    ]
