# Generated by Django 2.1.2 on 2018-12-03 08:21

from django.db import migrations

def create_pagefragments(apps, schema_editor):
    PageFragment = apps.get_model('page_fragments', 'PageFragment')

    PageFragment.objects.update_or_create(
        identifier='welcome',
        defaults={'content_nl': 'Welkom!',
                  'content_en': 'Welcome to the **Vespa-Watch** website'},
    )

    PageFragment.objects.update_or_create(
        identifier='terms_of_service',
        defaults={'content_nl': 'Terms of service - NL',
                  'content_en': 'Terms of service - EN'},
    )

def create_species(apps, schema_editor):
    Taxon = apps.get_model('vespawatch', 'Taxon')

    Taxon.objects.bulk_create(
        [# Taxa that are pushed and pulled
         Taxon(name="Vespa velutina",
               vernacular_name_nl="Aziatische hoornaar",
               vernacular_name_en="Asian hornet",
               identification_priority=True,
               inaturalist_push_taxon_id=119019,
               inaturalist_pull_taxon_ids=[119019, 560197]),
         Taxon(name="Vespa crabro",
               vernacular_name_nl="Europese hoornaar",
               vernacular_name_en="European Hornet",
               identification_priority=True,
               inaturalist_push_taxon_id=54327, inaturalist_pull_taxon_ids=[54327]),
         # Species that are only pushed, but never pulled
         Taxon(name="Vespula germanica",
               vernacular_name_nl="Duitse wesp",
               vernacular_name_en="German Yellowjacket",
               identification_priority=False,
               inaturalist_push_taxon_id=126155,
               inaturalist_pull_taxon_ids=[]),
         Taxon(name="Apis mellifera",
               vernacular_name_nl="Honingbij",
               vernacular_name_en="Honey Bee",
               identification_priority=False,
               inaturalist_push_taxon_id=47219,
               inaturalist_pull_taxon_ids=[]),
         Taxon(name="Insecta",
               vernacular_name_nl="Insect",
               vernacular_name_en="Insect",
               identification_priority=False,
               inaturalist_push_taxon_id=47158,
               inaturalist_pull_taxon_ids=[]),
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_species),
        migrations.RunPython(create_pagefragments),
    ]
