# Generated by Django 2.1.2 on 2018-11-15 09:03

from django.db import migrations


def create_pagefragments(apps, schema_editor):
    PageFragment = apps.get_model('page_fragments', 'PageFragment')

    PageFragment.objects.update_or_create(
        identifier='welcome',
        defaults={'content_nl': 'Welkom!',
                  'content_en': 'Welcome to the **Vespa-Watch** website'},
    )

    PageFragment.objects.update_or_create(
        identifier='terms_of_service',
        defaults={'content_nl': 'Terms of service - NL',
                  'content_en': 'Terms of service - EN'},
    )

def create_species(apps, schema_editor):
    Species = apps.get_model('vespawatch', 'Species')

    Species.objects.bulk_create(
        [# Species that are pushed and pulled
         Species(name="Vespa velutina",
                 vernacular_name_nl="Aziatische hoornaar", vernacular_name_en="Asian hornet",
                 inaturalist_push_taxon_id=119019, inaturalist_pull_taxon_ids=[119019, 560197]),
         Species(name="Vespa crabro",
                 vernacular_name_nl="Europese hoornaar", vernacular_name_en="European Hornet",
                 inaturalist_push_taxon_id=54327, inaturalist_pull_taxon_ids=[54327]),
         # Species that are only pushed, but never pulled
         Species(name="Vespula germanica",
                 vernacular_name_nl="Duitse wesp", vernacular_name_en="German Yellowjacket",
                 inaturalist_push_taxon_id=126155, inaturalist_pull_taxon_ids=[]),
         Species(name="Apis mellifera",
                 vernacular_name_nl="Honingbij", vernacular_name_en="Honey Bee",
                 inaturalist_push_taxon_id=47219, inaturalist_pull_taxon_ids=[]),
         Species(name="Insecta",
                 vernacular_name_nl="Insect", vernacular_name_en="Insect",
                 inaturalist_push_taxon_id=47158, inaturalist_pull_taxon_ids=[]),
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_species),
        migrations.RunPython(create_pagefragments),
    ]
