# Generated by Django 2.1.2 on 2018-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
