# Generated by Django 2.1.2 on 2018-11-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InatObsToDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inaturalist_id', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='individualpicture',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='vespawatch.Individual'),
        ),
        migrations.AlterField(
            model_name='nestpicture',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='vespawatch.Nest'),
        ),
    ]
