# Generated by Django 2.1.1 on 2018-10-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0003_observation_originates_in_vespawatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='originates_in_vespawatch',
            field=models.BooleanField(default=True, help_text='The observation was first created in VespaWatch, not iNaturalist'),
        ),
    ]
