# Generated by Django 2.1.2 on 2018-11-19 14:52

from django.db import migrations, models
import vespawatch.models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0003_auto_20181115_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='identification_picture',
            field=models.ImageField(blank=True, null=True, upload_to=vespawatch.models.Species.get_file_path),
        ),
        migrations.AddField(
            model_name='species',
            name='identification_priority',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
