# Generated by Django 2.1.2 on 2019-01-07 09:58

from django.db import migrations, models
import vespawatch.models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0003_managementaction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='observation_time',
            field=models.DateTimeField(validators=[vespawatch.models.no_future], verbose_name='Observation date'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='observation_time',
            field=models.DateTimeField(validators=[vespawatch.models.no_future], verbose_name='Observation date'),
        ),
    ]
