# Generated by Django 2.1.1 on 2018-10-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0004_auto_20181009_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='behaviour',
            field=models.CharField(blank=True, choices=[('FO', 'Fouraging'), ('HU', 'Hunting at hive'), ('FL', 'At flower'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='individual_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_approve_data_distribution',
            field=models.NullBooleanField(help_text='The observer approves that the recorded observation will be distributed to third parties'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_approve_data_process',
            field=models.NullBooleanField(help_text='The observer approves that his data will be processed by Vespa-Watch'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_approve_display',
            field=models.NullBooleanField(help_text='The observer approves that the observation will be displayed on the Vespa-Watch map'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_is_beekeeper',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
