# Generated by Django 2.1.2 on 2018-11-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0004_auto_20181119_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Species',
            new_name='Taxon',
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'verbose_name_plural': 'taxa'},
        ),
    ]
