# Generated by Django 2.1.2 on 2019-01-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0005_identificationcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificationcard',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='identificationcard',
            name='description_nl',
        ),
    ]
