# Generated by Django 2.1.2 on 2018-11-26 13:16

from django.db import migrations, models
import django.db.models.deletion
import vespawatch.models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0005_auto_20181126_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='species',
            field=models.ForeignKey(default=vespawatch.models.get_default_taxon_id, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.Taxon'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='species',
            field=models.ForeignKey(default=vespawatch.models.get_default_taxon_id, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.Taxon'),
        ),
    ]
