# Generated by Django 2.1.2 on 2018-11-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0006_auto_20181126_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='species',
            new_name='taxon',
        ),
        migrations.RenameField(
            model_name='nest',
            old_name='species',
            new_name='taxon',
        ),
    ]
