# Generated by Django 2.1.2 on 2019-01-21 13:09

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0006_auto_20190121_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationcard',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='identificationcard',
            name='description_en',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identificationcard',
            name='description_nl',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
