# Generated by Django 2.1.5 on 2019-01-28 14:24

from django.db import migrations

def create_pagefragments(apps, schema_editor):
    PageFragment = apps.get_model('page_fragments', 'PageFragment')

    PageFragment.objects.update_or_create(
        identifier='identification_page',
        defaults={'content_nl': 'Identification page content (NL)',
                  'content_en': 'Identification page content (EN)'},
    )

    PageFragment.objects.update_or_create(
        identifier='about_page',
        defaults={'content_nl': 'About page content (NL)',
                  'content_en': 'About page content (EN)'},
    )

class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0007_auto_20190121_1409'),
    ]

    operations = [
        migrations.RunPython(create_pagefragments),
    ]
