# Generated by Django 2.1.2 on 2018-11-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0007_auto_20181126_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxon',
            old_name='identification_picture',
            new_name='identification_picture_individual',
        ),
    ]
