# Generated by Django 2.1.2 on 2018-11-26 15:28

from django.db import migrations, models
import vespawatch.models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0008_auto_20181126_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='identification_picture_nest',
            field=models.ImageField(blank=True, null=True, upload_to=vespawatch.models.Taxon.get_file_path),
        ),
    ]
