# Generated by Django 2.1.2 on 2018-10-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0009_auto_20181011_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='inaturalist_pull_taxons_id',
            new_name='inaturalist_pull_taxon_ids',
        ),
    ]
