# Generated by Django 2.1.5 on 2019-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0009_add_new_page_fragments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='observer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='observer_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='observer_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='observer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='height',
            field=models.CharField(blank=True, choices=[('BELOW_4_M', 'Below 4 meters'), ('BELOW_4_M', 'Above 4 meters')], max_length=50, verbose_name='Nest height'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='observer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='observer_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='observer_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='observer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='size',
            field=models.CharField(blank=True, choices=[('LESS_25_CM', 'Less than 25cm'), ('MORE_25_CM', 'More than 25cm')], max_length=50, verbose_name='Nest size'),
        ),
    ]
