# Generated by Django 2.1.2 on 2018-11-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0009_taxon_identification_picture_nest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='observer_title',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='observer_title',
        ),
    ]
