# Generated by Django 2.1.2 on 2018-10-11 13:19

from django.db import migrations

def create_species(apps, schema_editor):
    Species = apps.get_model('vespawatch', 'Species')

    Species.objects.bulk_create(
        [# Species that are pushed and pulled
         Species(name="Vespa velutina",
                 vernacular_name_nl="Aziatische hoornaar", vernacular_name_en="Asian Predatory Wasp",
                 inaturalist_push_taxon_id=119019, inaturalist_pull_taxon_ids=[119019, 560197]),
         Species(name="Vespa crabro",
                 vernacular_name_nl="Europese hoornaar", vernacular_name_en="European Hornet",
                 inaturalist_push_taxon_id=54327, inaturalist_pull_taxon_ids=[54327]),
         # Species that are only pushed, but never pulled
         Species(name="Vespula germanica",
                 vernacular_name_nl="Duitse wesp", vernacular_name_en="German Yellowjacket",
                 inaturalist_push_taxon_id=126155, inaturalist_pull_taxon_ids=[]),
         Species(name="Apis mellifera",
                 vernacular_name_nl="Honingbij", vernacular_name_en="Honey Bee",
                 inaturalist_push_taxon_id=47219, inaturalist_pull_taxon_ids=[]),
         Species(name="Insecta",
                 vernacular_name_nl="Insect", vernacular_name_en="Insect",
                 inaturalist_push_taxon_id=47158, inaturalist_pull_taxon_ids=[]),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0010_auto_20181011_1506'),
    ]

    operations = [
        migrations.RunPython(create_species),
    ]
