# Generated by Django 2.1.2 on 2018-11-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0010_auto_20181126_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='nest',
            old_name='location',
            new_name='address',
        ),
    ]
