# Generated by Django 2.1.5 on 2019-03-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0010_auto_20190318_1408'),
        ('vespawatch', '0010_individualobservationwarning_nestobservationwarning'),
    ]

    operations = [
    ]
