# Generated by Django 2.1.5 on 2019-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0011_auto_20190429_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='behaviour',
            field=models.CharField(blank=True, choices=[('HU', 'Hunting at beehive'), ('FL', 'Drinking nectar on flower'), ('WO', 'Near wood source'), ('WA', 'Near water source'), ('FG', 'Flying'), ('CA', 'Captured'), ('DE', 'Dead'), ('OT', 'Other')], max_length=2, null=True, verbose_name='Behaviour'),
        ),
    ]
