# Generated by Django 2.1.2 on 2018-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0011_auto_20181128_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='height',
            field=models.CharField(blank=True, choices=[('BELOW_4_M', 'Below 4 meters'), ('BELOW_4_M', 'Above 4 meters')], max_length=50),
        ),
        migrations.AddField(
            model_name='nest',
            name='size',
            field=models.CharField(blank=True, choices=[('LESS_25_CM', 'Less than 25cm'), ('MORE_25_CM', 'More than 25cm')], max_length=50),
        ),
    ]
