# Generated by Django 2.1.5 on 2019-03-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0011_merge_20190318_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='inat_vv_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nest',
            name='inat_vv_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
