# Generated by Django 2.1.2 on 2018-11-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0011_species_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='subject',
            field=models.CharField(choices=[('NE', 'Nest'), ('SP', 'Individual')], max_length=2),
        ),
        migrations.AlterField(
            model_name='observationpicture',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vespawatch.Observation'),
        ),
    ]
