# Generated by Django 2.2.1 on 2019-05-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0012_auto_20190429_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='observer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='nest',
            name='observer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
