# Generated by Django 2.1.2 on 2018-11-06 09:56

from django.db import migrations

def nop(apps, schema_editor):
    pass

def create_welcome_pagefragment(apps, schema_editor):
    PageFragment = apps.get_model('page_fragments', 'PageFragment')

    PageFragment.objects.update_or_create(
        identifier='welcome',
        defaults={'content_nl': 'Welkom!',
                  'content_en': 'Welcome to the **Vespa-Watch** website'},
    )

class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0012_auto_20181106_0932'),
    ]

    operations = [
        migrations.RunPython(create_welcome_pagefragment, nop),
    ]
