# Generated by Django 2.2.1 on 2019-05-08 13:21

from django.db import migrations

def merge_names(apps, schema_editor):
    Individual = apps.get_model('vespawatch', 'Individual')
    Nest = apps.get_model('vespawatch', 'Nest')

    for ObsModel in [Individual, Nest]:
        for obs in ObsModel.objects.all():
            obs.observer_name = f'{obs.observer_first_name} {obs.observer_last_name}'
            obs.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0013_auto_20190508_1520'),
    ]

    operations = [
        migrations.RunPython(merge_names),
    ]
