# Generated by Django 2.1.2 on 2018-11-06 10:12

from django.db import migrations

def rename_vespa_velutina(apps, schema_editor):
    Species = apps.get_model('vespawatch', 'Species')
    sp = Species.objects.get(vernacular_name_en="Asian Predatory Wasp")
    sp.vernacular_name_en = "Asian hornet"
    sp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0013_auto_20181106_1056'),
    ]

    operations = [
        migrations.RunPython(rename_vespa_velutina)
    ]
