# Generated by Django 2.1.2 on 2018-11-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vespawatch.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vespawatch', '0014_rename_asian_hornet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirefightersZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vespawatch.FirefightersZone')),
            ],
        ),
        migrations.AlterField(
            model_name='observationpicture',
            name='image',
            field=models.ImageField(upload_to=vespawatch.models.ObservationPicture.get_file_path),
        ),
    ]
