# Generated by Django 2.2.1 on 2019-05-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0014_merge_observer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='observer_first_name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='observer_last_name',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='observer_first_name',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='observer_last_name',
        ),
    ]
