# Generated by Django 2.1.2 on 2018-11-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0014_rename_asian_hornet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originates_in_vespawatch', models.BooleanField(default=True, help_text='The observation was first created in VespaWatch, not iNaturalist')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('observation_time', models.DateTimeField()),
                ('comments', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('inaturalist_id', models.BigIntegerField(blank=True, null=True)),
                ('inaturalist_species', models.CharField(blank=True, max_length=100, null=True)),
                ('observer_title', models.CharField(blank=True, max_length=50, null=True)),
                ('observer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('observer_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('observer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('observer_is_beekeeper', models.NullBooleanField()),
                ('observer_approve_data_process', models.NullBooleanField(help_text='The observer approves that his data will be processed by Vespa-Watch')),
                ('observer_approve_display', models.NullBooleanField(help_text='The observer approves that the observation will be displayed on the Vespa-Watch map')),
                ('observer_approve_data_distribution', models.NullBooleanField(help_text='The observer approves that the recorded observation will be distributed to third parties')),
                ('individual_count', models.IntegerField(blank=True, null=True)),
                ('behaviour', models.CharField(blank=True, choices=[('FO', 'Fouraging'), ('HU', 'Hunting at hive'), ('FL', 'At flower'), ('OT', 'Other')], max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='individual_pictures/')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vespawatch.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Nest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originates_in_vespawatch', models.BooleanField(default=True, help_text='The observation was first created in VespaWatch, not iNaturalist')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('observation_time', models.DateTimeField()),
                ('comments', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('inaturalist_id', models.BigIntegerField(blank=True, null=True)),
                ('inaturalist_species', models.CharField(blank=True, max_length=100, null=True)),
                ('observer_title', models.CharField(blank=True, max_length=50, null=True)),
                ('observer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('observer_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('observer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('observer_is_beekeeper', models.NullBooleanField()),
                ('observer_approve_data_process', models.NullBooleanField(help_text='The observer approves that his data will be processed by Vespa-Watch')),
                ('observer_approve_display', models.NullBooleanField(help_text='The observer approves that the observation will be displayed on the Vespa-Watch map')),
                ('observer_approve_data_distribution', models.NullBooleanField(help_text='The observer approves that the recorded observation will be distributed to third parties')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.Nest')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.Species')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NestPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nest_pictures/')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vespawatch.Nest')),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='nest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vespawatch.Nest'),
        ),
        migrations.AddField(
            model_name='individual',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.Species'),
        ),
    ]
