# Generated by Django 2.2.1 on 2019-05-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0015_auto_20190508_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='observer_is_beekeeper',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='observer_is_beekeeper',
        ),
    ]
