# Generated by Django 2.1.2 on 2018-11-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0015_auto_20181106_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.FirefightersZone'),
        ),
    ]
