# Generated by Django 2.1.2 on 2018-11-06 15:22

from django.db import migrations

def delete_observations(apps, schema_editor):
    Observation = apps.get_model('vespawatch', 'Observation')
    ObservationPicture = apps.get_model('vespawatch', 'ObservationPicture')
    for pic in ObservationPicture.objects.all():
        pic.delete()
    for observation in Observation.objects.all():
        observation.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0016_auto_20181106_1617'),
    ]

    operations = [
        migrations.RunPython(delete_observations)
    ]
