# Generated by Django 2.2.1 on 2019-05-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0013_auto_20190412_1020'),
        ('vespawatch', '0016_auto_20190508_1539'),
    ]

    operations = [
    ]
