# Generated by Django 2.1.2 on 2018-11-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0017_auto_20181106_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='species',
        ),
        migrations.RemoveField(
            model_name='observationpicture',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='managementaction',
            name='observation',
        ),
        migrations.AddField(
            model_name='managementaction',
            name='nest',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.Nest'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='ObservationPicture',
        ),
    ]
