# Generated by Django 2.1.5 on 2019-05-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0017_merge_20190517_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='behaviour',
            field=models.CharField(blank=True, choices=[('HU', 'Hunting at beehive'), ('FL', 'Drinking nectar on flower'), ('WO', 'Near wood source'), ('WA', 'Near water source'), ('FG', 'Flying'), ('CA', 'Captured'), ('DE', 'Dead'), ('OT', 'Other')], max_length=2, null=True, verbose_name='Behaviour'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.Taxon'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.Taxon'),
        ),
    ]
