# Generated by Django 2.1.2 on 2018-11-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0016_auto_20181106_1515'),
        ('vespawatch', '0018_auto_20181106_1635'),
    ]

    operations = [
    ]
