# Generated by Django 2.1.2 on 2018-11-06 20:38

from django.db import migrations, models
import vespawatch.models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0019_merge_20181106_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpicture',
            name='image',
            field=models.ImageField(upload_to=vespawatch.models.IndividualPicture.get_file_path),
        ),
        migrations.AlterField(
            model_name='nestpicture',
            name='image',
            field=models.ImageField(upload_to=vespawatch.models.NestPicture.get_file_path),
        ),
    ]
