# Generated by Django 2.2.1 on 2019-05-27 09:46

from django.db import migrations

FRENCH_TEXTS = {
    'welcome':

"""Le frelon asiatique a été observé en Belgique pour la première fois en 2011. Depuis, l'espèce s'est rapidement 
propagée. Cet insecte est originaire de Chine. Il s'attaque aux abeilles et à d'autres insectes et est considéré comme
une espèce exotique envahissante. En Belgique, sa propagation est surveillée. La population est gérée via la destruction 
des nids.

La surveillance nécessite de nombreuses paires d'yeux, y compris la votre ! Vous découvrirez ici comment vous pouvez 
aider au suivi du frelon asiatique grace au projet de sciences citoyennes Vespa-Watch. Vos données seront utilisées pour 
la recherche et le contrôle des populations.

[Activités](https://www.honeybeevalley.eu/kalender) - [Impliquez-vous](https://vespawatch.be/get-involved/)""",

    'about_privacypolicy':

"""
Vie privée et droit d'auteur
============================

Merci pour votre intérêt envers le projet Vespa-Watch, et pour votre aide dans la collecte d'informations sur le 
frelon asiatique. Sur cette page, nous expliquons comment nous gérons vos données personnelles et les données collectées
via ce site web. 

Que se passe-t-il avec mes données
----------------------------------

Le site web de Vespa-Watch est géré par [l'Institut Flamand de Recherche sur la Nature et les Forêts (INBO)](https://www.inbo.be/).
Afin de protéger l'environnement et de permettre la recherche scientifique, les données collectées (y compris les photos, mais 
en excluant les informations personnelles) sont rendues publiques sous licence [Creative Commons Zero](https://creativecommons.org/publicdomain/zero/1.0/), en accord avec [la 
politique de données d'INBO](https://www.inbo.be/en/open-data-policy).

Les données sont synchronisées avec [iNaturalist](https://www.inaturalist.org/projects/vespa-watch), une plateforme globale permettant d'enregistrer les observations de 
biodiversité. Les données enregistrées via le site Vespa-Watch sont visibles sur iNaturalist sous un nom d'utilsateur 
générique (Vespa-Watch). De façons similaires, les données d'iNaturalist sont également collectées par Vespa-Watch. Après
validation, les données sont publiées au [GBIF](https://www.gbif.org/), un aggrégateur global de données de biodiversité. De cette façon, les 
données de Vespa-Watch peuvent être utilisées dans le monde entier pour la recherche, la gestion et comme support à des 
décisions politiques. Elles peuvent également être reprises et apparaitrent sur d'autres sites tels que [waarnemingen.be](https://waarnemingen.be/) et 
[observation.org](https://observation.org/).

Nom et adresse e-mail
---------------------

Le site Vespa-Watch ne nécessite pas de s'enregistrer afin de signaler une observation de frelon asiatique. Ceci permet
de garder la contribution facile, et d'avoir des données rapidement disponibles. Cependant, lors du signalement nous 
collectons votre nom et votre adresse e-mail. Ces informations sont uniquement visibles par les experts pour une utilisation
dans le cadre du projet (par exemple pour valider l'observation). Vos données personnelles ne 
sont en aucun cas partagées avec des tiers ni rendues visibles sur le site web. Lors du partage de données avec 
iNaturalist, les données sont publiées sous un nom d'utilisateur générique (Vespa-Watch) et votre nom ne sera pas 
rendu public. Si vous le souhaitez, vous pouvez bien sûr également choisir de créer un compte personnel sur 
[iNaturalist](https://www.inaturalist.org/), après quoi Vespa-Watch pourra également utiliser vos données.

Combien de temps mes données sont-elles conservées ?
----------------------------------------------------

Les données soumises seront conservées indéfiniment, afin de permette à l'avenir la conservation et l'étude 
des espèces soumises. Toutes les données sont conservées sur un serveur sécurisé à INBO. Toutes les données sont 
partagées avec [iNaturalist](https://www.inaturalist.org/), et une fois validées avec le [réseau GBIF](https://www.gbif.org/).


Qui a accès à mes données personnelles ?
----------------------------------------
Aucune personne extérieure au projet Vespa-Watch n'a accès à vos données personnelles. Excepté en cas d'obligation légale, 
vos données ne seront pas rendues disponibles à des tiers (y compris à des chercheurs externes au projet), sauf s'ils ont 
un lien direct avec leur projet et après avoir obtenu votre consentement. Si vous partagez une numéro de téléphone
lorsque vous signalez un nid, ce numéro pourra être utilisé par les pompiers afin d'obtenir des informations 
pertinentes additionelles (accessibilité du nid, rendez-vous, ...) pour planifier puis exécuter la destruction du nid.
Vos données personnelles ne seront pas utilisés pour d'autres causes, ni partagées avec des tiers, ni affichés sur le
site web.
"""
}


def noop(apps, schema_editor):
    pass


def _update_pf_fr_text(pf_model, pf_identifier, content_fr):
    f = pf_model.objects.get(identifier=pf_identifier)
    f.content_fr = content_fr
    f.save(update_fields=['content_fr'])


def create_or_update_pagefragments(apps, schema_editor):
    PageFragment = apps.get_model('page_fragments', 'PageFragment')

    for identifier, content_fr in FRENCH_TEXTS.items():
        _update_pf_fr_text(pf_model=PageFragment, pf_identifier=identifier, content_fr=content_fr)


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0020_auto_20190527_1116'),
        ('page_fragments', '0002_pagefragment_content_fr')
    ]

    operations = [
        migrations.RunPython(create_or_update_pagefragments, noop),
    ]
