# Generated by Django 2.2.1 on 2019-06-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0020_auto_20190603_1031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individual',
            unique_together={('taxon', 'observation_time', 'latitude', 'longitude', 'comments')},
        ),
        migrations.AlterUniqueTogether(
            name='nest',
            unique_together={('taxon', 'observation_time', 'latitude', 'longitude', 'comments')},
        ),
    ]
