# Generated by Django 2.1.5 on 2019-06-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0021_auto_20190603_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpicture',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='vespawatch.Individual'),
        ),
        migrations.AlterField(
            model_name='nestpicture',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='vespawatch.Nest'),
        ),
    ]
