# Generated by Django 2.1.2 on 2018-11-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0021_auto_20181107_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='observer_approve_data_distribution',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='observer_approve_data_process',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='observer_approve_display',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='observer_approve_data_distribution',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='observer_approve_data_process',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='observer_approve_display',
        ),
    ]
