# Generated by Django 2.1.5 on 2019-06-20 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0022_auto_20190620_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualpicture',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2000, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nestpicture',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2000, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
