# Generated by Django 2.1.2 on 2018-11-12 10:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0022_auto_20181107_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='firefighterszone',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
