# Generated by Django 2.1.8 on 2019-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0023_auto_20190620_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='address',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='address',
        ),
        migrations.AlterField(
            model_name='individual',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments are public: use them to describe your observation and help verification.', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='nest',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments are public: use them to describe your observation and help verification.', verbose_name='Comments'),
        ),
    ]
