# Generated by Django 2.1.2 on 2018-11-14 14:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0023_firefighterszone_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firefighterszone',
            name='polygon',
        ),
        migrations.AddField(
            model_name='firefighterszone',
            name='mpolygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
