# Generated by Django 2.1.2 on 2018-11-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0024_auto_20181114_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.FirefightersZone'),
        ),
        migrations.AddField(
            model_name='nest',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vespawatch.FirefightersZone'),
        ),
    ]
