# Generated by Django 2.1.8 on 2019-07-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0025_auto_20190725_1025'),
        ('vespawatch', '0024_auto_20190719_1446'),
    ]

    operations = [
    ]
