# Generated by Django 2.1.8 on 2019-07-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0025_auto_20190725_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='nest',
        ),
    ]
