# Generated by Django 2.1.8 on 2019-07-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0026_merge_20190725_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementaction',
            name='outcome',
            field=models.CharField(choices=[('FD', 'Full destruction, no debris'), ('PD', 'Partial destruction/debris left'), ('ND', 'Empty nest, nothing done'), ('UK', 'Unknown')], max_length=2, verbose_name='Outcome'),
        ),
    ]
