# Generated by Django 2.1.8 on 2019-07-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0028_managementaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='managementaction',
            name='nest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vespawatch.Nest'),
        ),
        migrations.AlterField(
            model_name='managementaction',
            name='outcome',
            field=models.CharField(choices=[('CM', 'Full destruction, no debris'), ('PD', 'Partial destruction/debris left'), ('ND', 'Empty nest, nothing done'), ('UK', 'Unknown')], max_length=2, verbose_name='Outcome'),
        ),
    ]
