# Generated by Django 2.1.8 on 2019-07-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0029_auto_20190729_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='expert_vv_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managementaction',
            name='outcome',
            field=models.CharField(choices=[('FD', 'Full destruction, no debris'), ('PD', 'Partial destruction/debris left'), ('ND', 'Empty nest, nothing done'), ('UK', 'Unknown')], max_length=2, verbose_name='Outcome'),
        ),
    ]
