# Generated by Django 2.1.8 on 2019-07-29 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('vespawatch', '0030_auto_20190729_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization')),
                ('description', models.TextField(blank=True, help_text='Description of your (organizations) activities', verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone number')),
                ('email_notification', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='nest',
            name='expert_vv_confirmed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Confirmed by expert'),
        ),
    ]
