# Generated by Django 2.1.8 on 2019-07-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0032_auto_20190730_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipality'),
        ),
    ]
