# Generated by Django 2.1.8 on 2019-10-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0026_remove_individual_nest'),
        ('vespawatch', '0033_nest_municipality'),
    ]

    operations = [
    ]
