# Generated by Django 2.1.15 on 2020-01-20 09:25

import django.core.validators
from django.db import migrations, models
import vespawatch.models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0034_merge_20191014_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationcard',
            name='identification_picture',
            field=models.ImageField(blank=True, null=True, upload_to=vespawatch.models.IdentificationCard.get_file_path, verbose_name='Photo for identification'),
        ),
        migrations.AlterField(
            model_name='managementaction',
            name='action_time',
            field=models.DateTimeField(verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='managementaction',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration (in minutes)'),
        ),
        migrations.AlterField(
            model_name='managementaction',
            name='person_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reported by'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, help_text='Describe the activities of your organization / business.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='Get email notifications for new nests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization / business'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers are allowed.')], verbose_name='Telephone number'),
        ),
    ]
