# Generated by Django 2.1.15 on 2020-01-20 13:37

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0035_auto_20200120_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationcard',
            name='description_fr',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='vernacular_name_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vernacular name'),
        ),
    ]
