# Generated by Django 2.2.13 on 2020-09-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0036_auto_20200120_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementaction',
            name='outcome',
            field=models.CharField(choices=[('PP', 'professional permas - D treatment'), ('PC', 'Classic permas - D treatment'), ('FD', 'Complete manual removal'), ('PD', 'Partial manual removal'), ('ND', 'Empty nest, nothing done'), ('UK', 'Unknown')], max_length=2, verbose_name='Outcome'),
        ),
    ]
