# Generated by Django 2.1.15 on 2020-01-20 13:25

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_fragments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefragment',
            name='content_fr',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
