# Generated by Django 2.2.1 on 2019-05-27 09:52

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_fragments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefragment',
            name='content_fr',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
